name: Deploy Web
on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/CHANGELOG.md'
      - '.github/workflows/deploy-web.yml'
jobs:
  build-web-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: 'add'
          database_id: ${{ secrets.DATABASE_ID }}
          digitalocean_token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
      - uses: ./.github/actions/build-and-push-docker
        with:
          app-name: web
          digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          build-args: |
            PUBLIC_URL=https://regels.overheid.nl/web/
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            CMS_URL=http://cms:9001
            NEXT_PUBLIC_CMS_URL=https://regels.overheid.nl/cms
      - uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
        with:
          action: 'remove'
          database_id: ${{ secrets.DATABASE_ID }}
          digitalocean_token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
  deploy-web-image:
    runs-on: ubuntu-latest
    needs: build-web-image
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/upgrade-helm
        with:
          app-name: web
          release-name: web
          digitalocean-access-token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
          cluster-id: '${{ secrets.DIGITALOCEAN_PRODUCTION_CLUSTER_ID }}'
